DROP TABLE IF EXISTS session ;
CREATE TABLE session (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,
	token VARCHAR(300) NOT NULL,
	ip_address VARCHAR(100) NOT NULL,
	useragent VARCHAR(2) NOT NULL,
	created_at VARCHAR(15) NOT NULL,
	expiration VARCHAR(15) NOT NULL,
	CONSTRAINT uq_session_user_id UNIQUE (user_id),
	CONSTRAINT uq_session_token UNIQUE (token)
);